### ISSUE TITLE
在下可是草帽不是猫？

### ISSUE THREAD

**Issue by fastLazy** [strawhatboy/ztmz_pacenote#1]

**Comment by fastLazy** [comment]
我现在RBR的中文路书也用的ZTMZ的

**Comment by strawhatboy** [comment]
> 我现在RBR的中文路书也用的ZTMZ的

是我😂 多谢支持！

**Comment by fastLazy** [comment]
> > 我现在RBR的中文路书也用的ZTMZ的
> 
> 是我joy 多谢支持！

互相支持，simRallyCn也需要你的支持
