### ISSUE TITLE
ZTMZ pacenote tool wont start on startup

### ISSUE THREAD

**Issue by dimtsile** [strawhatboy/ztmz_pacenote#2]
Hello!!!

I want to make the tool start on windows stratup but it doesn't work. It pops up an error or never opens. If i double click on it it starts fine. I've made a schedule in Windows Task Scheduler so it starts on Win startup. I'm using Task Scheduler for other programs and they work fine. How can i solve this?

Edit...
I've solved the issue by putting the ahortcut of the tool in the windows startup folder, which ironically doesn't work for the othe apps i mentioned above.😅

**Comment by strawhatboy** [comment]
> Hello!!!
> 
> I want to make the tool start on windows stratup but it doesn't work. It pops up an error or never opens. If i double click on it it starts fine. I've made a schedule in Windows Task Scheduler so it starts on Win startup. I'm using Task Scheduler for other programs and they work fine. How can i solve this?
> 
> Edit... I've solved the issue by putting the ahortcut of the tool in the windows startup folder, which ironically doesn't work for the othe apps i mentioned above.😅

Hi there,

I just tried that with my win11 22H2 task scheduler, and it seems to be working well. I guess your case could be caused by something wrong in the task's settings. Maybe the following steps could help:
1. In the "General" page of the task, make sure the task is running with your current logon user and make sure the option "Run only when user is logged on" is selected.
2. In the "Triggers" page, make sure the trigger is "At log on" but not "At startup". (The program would need Windows desktop available, so "At log on" should be necessary.)
3. In the "Conditions" page, make sure to **uncheck** "Start the task only if the computer is on AC power", if you're on a laptop without plugged in.
4. In the "Actions" page, try to add the *.exe file to "Program/script", and the "Start in (optional)" to be the same as that in the properties of ZTMZ shortcut on your desktop.

It should work if settings above was considered. :)

Attached my task xml just for your information.
```xml
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2023-03-21T16:19:41.3946916</Date>
    <Author>ANDY-SURFACE\straw</Author>
    <URI>\MYTASKS\ztmz</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>ANDY-SURFACE\straw</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-1311307048-3256707406-3901527317-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\Users\straw\AppData\Local\Programs\ztmzclub_pacenotetool\ZTMZ.PacenoteTool.exe</Command>
      <WorkingDirectory>C:\Users\straw\AppData\Local\Programs\ztmzclub_pacenotetool</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
```

**Comment by dimtsile** [comment]
> > Hello!!!
> > I want to make the tool start on windows stratup but it doesn't work. It pops up an error or never opens. If i double click on it it starts fine. I've made a schedule in Windows Task Scheduler so it starts on Win startup. I'm using Task Scheduler for other programs and they work fine. How can i solve this?
> > Edit... I've solved the issue by putting the ahortcut of the tool in the windows startup folder, which ironically doesn't work for the othe apps i mentioned above.😅
> 
> Hi there,
> 
> I just tried that with my win11 22H2 task scheduler, and it seems to be working well. I guess your case could be caused by something wrong in the task's settings. Maybe the following steps could help:
> 
> 1. In the "General" page of the task, make sure the task is running with your current logon user and make sure the option "Run only when user is logged on" is selected.
> 2. In the "Triggers" page, make sure the trigger is "At log on" but not "At startup". (The program would need Windows desktop available, so "At log on" should be necessary.)
> 3. In the "Conditions" page, make sure to **uncheck** "Start the task only if the computer is on AC power", if you're on a laptop without plugged in.
> 4. In the "Actions" page, try to add the *.exe file to "Program/script", and the "Start in (optional)" to be the same as that in the properties of ZTMZ shortcut on your desktop.
> 
> It should work if settings above was considered. :)
> 
> Attached my task xml just for your information.
> 
> ```
> <?xml version="1.0" encoding="UTF-16"?>
> <Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
>   <RegistrationInfo>
>     <Date>2023-03-21T16:19:41.3946916</Date>
>     <Author>ANDY-SURFACE\straw</Author>
>     <URI>\MYTASKS\ztmz</URI>
>   </RegistrationInfo>
>   <Triggers>
>     <LogonTrigger>
>       <Enabled>true</Enabled>
>       <UserId>ANDY-SURFACE\straw</UserId>
>     </LogonTrigger>
>   </Triggers>
>   <Principals>
>     <Principal id="Author">
>       <UserId>S-1-5-21-1311307048-3256707406-3901527317-1001</UserId>
>       <LogonType>InteractiveToken</LogonType>
>       <RunLevel>LeastPrivilege</RunLevel>
>     </Principal>
>   </Principals>
>   <Settings>
>     <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
>     <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
>     <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
>     <AllowHardTerminate>true</AllowHardTerminate>
>     <StartWhenAvailable>false</StartWhenAvailable>
>     <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
>     <IdleSettings>
>       <StopOnIdleEnd>true</StopOnIdleEnd>
>       <RestartOnIdle>false</RestartOnIdle>
>     </IdleSettings>
>     <AllowStartOnDemand>true</AllowStartOnDemand>
>     <Enabled>true</Enabled>
>     <Hidden>false</Hidden>
>     <RunOnlyIfIdle>false</RunOnlyIfIdle>
>     <WakeToRun>false</WakeToRun>
>     <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
>     <Priority>7</Priority>
>   </Settings>
>   <Actions Context="Author">
>     <Exec>
>       <Command>C:\Users\straw\AppData\Local\Programs\ztmzclub_pacenotetool\ZTMZ.PacenoteTool.exe</Command>
>       <WorkingDirectory>C:\Users\straw\AppData\Local\Programs\ztmzclub_pacenotetool</WorkingDirectory>
>     </Exec>
>   </Actions>
> </Task>
> ```

Hello!
Thanks for the response!
I've found a solution on this matter.
Now i have a problem with the countdown audio files.
They are the only files that i can't make them work.
Can you please help me on this too?

**Comment by strawhatboy** [comment]
> Hello! Thanks for the response! I've found a solution on this matter. Now i have a problem with the countdown audio files. They are the only files that i can't make them work. Can you please help me on this too?

Yes, about the countdown files, they only work with the game **Richard Burns Rally** for now.
DirtRally series have inconsistent signals in their UDP packages for different game modes, that's why counting down was not supported.

**Comment by strawhatboy** [comment]
will add option "Start with Windows" in general settings page in 3.0 release.
